<?php
$links = [
    ['title' => 'admin', 'url' => 'admin/admin.php'],
    ['title' => 'check_box', 'url' => 'check_box.php'],
    ['title' => 'home', 'url' => 'home.php'],
    ['title' => 'tray', 'url' => 'tray.php'],
    ['title' => 'view', 'url' => 'view.php'],
    ['title' => 'coustmer', 'url' => 'coustmer/coustmer.php'],
    ['title' => 'FLEX', 'url' => 'css/FLEX.html'],
    ['title' => 'viewcontorl', 'url' => 'file/viewcontorl.php'],
    ['title' => 'view img', 'url' => 'file/viewimg.php'],
    ['title' => 'uplod file', 'url' => 'file/upload.php'],
    ['title' => 'fileform', 'url' => 'file/fileform.php'],
    ['title' => 'countery', 'url' => 'html/countery.html'],
    ['title' => 'footer', 'url' => 'html/footer.html'],
    ['title' => 'icon', 'url' => 'html/icon.html'],
    ['title' => 'nav', 'url' => 'html/nav.html'],
    ['title' => 'power', 'url' => 'html/power.html'],
    ['title' => 'adduserform', 'url' => 'php/adduserform.php'],
    ['title' => 'learn', 'url' => 'php/learn.php'],
    ['title' => 'search', 'url' => 'php/searchfrom.php'],
    ['title' => 'about', 'url' => 'php/about.php'],
    ['title' => 'contec lens', 'url' => 'prodect/contac.php'],
    ['title' => 'frame', 'url' => 'prodect/fram.php'],
    ['title' => 'Kids', 'url' => 'prodect/kids.php'],
    ['title' => 'last', 'url' => 'prodect/last.php'],
    ['title' => 'add iteamt', 'url' => 'prodect/add_iteam.php'],
    ['title' => 'Brand', 'url' => 'prodect/brand.php'],
    ['title' => 'new Company', 'url' => 'prodect/newcompany.php'],
    ['title' => 'new Brodect', 'url' => 'prodect/prodect.php'],
    ['title' => 'lens', 'url' => 'prodect/lens.php'],
    ['title' => 'lens type', 'url' => 'prodect/lens_type.php'],
    ['title' => 'Active', 'url' => 'sign/active.php'],
    ['title' => 'login', 'url' => 'sign/login.php'],
    ['title' => 'register', 'url' => 'sign/register.php'],
    ['title' => 'reset', 'url' => 'sign/reset.php'],
];
?>

